### ISSUE TITLE
Make catalog number box wider on Data Entry Screen

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1636]
Can we please make the Catalog Number box bigger on the Data Entry screen?
![ss_dataentry](https://user-images.githubusercontent.com/17605945/43616157-9c165baa-9667-11e8-89ac-2bedd5e0edcf.jpeg)

It's very tiny and I'm trying to enter numbers that are 15 characters long (e.g., UA2018-008-0008). Seems there's plenty of space to make the cat# field wider and the CustomID Type box smaller.

**Comment by AJLinn** [comment]
Is this something anyone else is interested in seeing adjusted or am i alone in my irritation of the small box?

**Comment by Jegelewicz** [comment]
The whole thing needs help, but for now I think your request should be accommodated. How difficult would it be to make this field larger perhaps at the expense of "custom ID type?

**Comment by brandon-s-thompson** [comment]
I agree.  A larger Catalog Number Box would help. Looks like there's room to borrow from the CustomID Type and Accn boxes.

**Comment by dustymc** [comment]
done
<img width="110" alt="screen shot 2018-09-05 at 4 26 20 pm" src="https://user-images.githubusercontent.com/5720791/45126490-75ebdc80-b128-11e8-84af-e50d9b2682c8.png">

**Comment by AJLinn** [comment]
Do I need to do something in my browser to make this take effect?
![ss_catnumber](https://user-images.githubusercontent.com/17605945/45920122-869c9200-be4c-11e8-85d1-ff1e44a0849c.jpeg)

**Comment by dustymc** [comment]
@AJLinn is this still a problem? Close or comment, please.

**Comment by AJLinn** [comment]
<img width="407" alt="Screen Shot 2021-01-21 at 10 13 55 AM" src="https://user-images.githubusercontent.com/17605945/105400565-902b9580-5bd1-11eb-9a50-cc70d498e76a.png">

I'm still getting a "scroll" effect when I have catalog numbers that require letters after the number (you can see the "UA" getting cut off that number above). Can you widen it juuuust a bit more please?

Thanks!

**Comment by dustymc** [comment]
I gave it two more characters in test.

<img width="109" alt="Screen Shot 2021-01-21 at 11 22 46 AM" src="https://user-images.githubusercontent.com/5720791/105401426-0e406a00-5bdb-11eb-857e-6a0f47e73424.png">


Does that stretch the form out in strange ways for anyone?

**Comment by ewommack** [comment]
Looks ok to me.

**Comment by AJLinn** [comment]
Thank you! I'll close for now and if someone has a major problem we can re-open.
