### ISSUE TITLE
Add all mollusca taxa from WoRMS to Arctos taxonomic tables

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1686]
While I'm filing this as a GitHub issue, it may be more appropriate to move this to the Taxonomic Committee.

The Denver Museum of Nature and Science Marine Invertebrate Collection is proposing that we consider uploading all taxa in Mollusca from the World Register of Marine Species (WoRMS) into the Arctos taxonomic tables.  Our collection is 99% mollusks and we add or modify anywhere between 5-20 marine taxa every week.  We can continue to do this but it is time-consuming and there is high potential for inconsistency.  We have used the Hierarchy Tool to clean up a lot of the taxonomy, but it's time consuming and only addresses existing taxa.  Uploading the  WoRMS data would add species not yet in Arctos and override current classification to be consistent with the new taxa.

WoRMS provides their taxa as a database dump to users.  (See http://www.marinespecies.org/usersrequest.php for the on-line form we would complete.)  There is no charge for this service (donations are appreciated).  Today, there are 138,936 names in Mollusca representing 116,077 species.  (See http://www.marinespecies.org/aphia.php?p=stats for these statistics.)   Of these, 48,159 are accepted species of which 15,131 are non-marine (freshwater or terrestrial) species.    The non-marine are available in WoRMS by transfer from Molluscabase (http://molluscabase.org/).  WoRMS is not strong on terrestrial species but the relationship with Molluscabase is rapidly adding these taxa.

Uploading the WoRMS data would overwrite all existing taxa to whatever the WoRMS classification is.  This would provide a one-time update, but might surprise some collection managers who find their specimens are now in a different family.  In the past, I've notified the collections manager when I want to update a taxon that is in their collection.  The WoRMS update will not tell us where the changes will be.

WoRMS provides their data as a JSON file that Dusty can convert to a .csv file for us to edit before the upload.  

Does everyone who uses any portion of the Mollusca taxonomic table support uploading the WoRMS data?  

Does anyone want to not include a certain group of taxa?

Should the upload include all taxa or only those that are "accepted."  I prefer to only upload "accepted" taxa.  I see no reason to add even more unaccepted taxa to Arctos.  

Note that Arctos Taxon Status table doesn't include the term "accepted."  Are we ok with using the Arctos term "valid" which, to me, has a slightly different meaning?

A WoRMS upload will not create relationships between synonyms etc.  That must still be done manually.  

Uploading the WoRMS data will do nothing to remove unaccepted/garbage/misspelled taxa.  That must still be done manually.

WoRMS would include the Author which is missing on many of our ITIS taxa.   

We have not yet seen a copy of the fields that are included but would try to get the most complete hierarchy available.  Some terms cannot be used in Arctos without adding additional classification levels.  For example:  Euthyneura (Infraclass) and Tectipleura (Subterclass).  Those using these taxa need to decide if these levels are important.  I've been deleting them and leaving the more common classification levels which is sufficient for our collection.
 
Having the WoRMS database as our taxonomic standard would, I think, make Arctos a more attractive database choice for any institution with a large mollusk collection.  It might be a test for uploading other marine species from WoRMS to Arctos.  

We may want to repeat the update periodically.  How often? I think there is a service to get updates but I don't understand the procedure yet.

For us, this is a high priority issue even though we have muddled along for several years now adding new taxa each week and cleaning up one or two families in the hierarchy tool.  Ideally, this would be addressed by the taxonomic committee at their next meeting.

**Comment by dustymc** [comment]
>Taxonomic Committee

done

> For example: .. (Infraclass)

Adding new ranks is fairly trivial, and the code table exists to prevent the introduction of garbage (misspellings and such), not to limit "real" terms. I have no objection to adding those - 100% the community's call.

While you can only manage "local" classification, you can prefer any. If these data are suitable for managing your collection, you could just provide them to GlobalNames (which could also deal with updates) and set your collection to prefer the remote classification. This would still require adding any new (bare) names to Arctos, but that should be trivial.

**Comment by sharpphyl** [comment]
WoRMS data is in GlobalNames and usually available when I "refresh/pull Global Names" unless there has been a change in WoRMS since they last updated GN.  

Where do I "prefer" a taxonomic group such as WoRMS and what happens when you prefer that source?   I can't find a reference to doing this in the handbook or on the taxonomic page.

**Comment by dustymc** [comment]
>Where

edit collection

>what

Docs are http://handbook.arctosdb.org/documentation/taxonomy.html#relationship-of-taxonomy-to-specimens, but the short version is that components (family, etc.) of the preferred classification are most associated with specimens - they're what you see on specimendetail, what the "family" (etc) search term hits, what's exported via DWC, etc.

**Comment by sharpphyl** [comment]
So we would have you change our Taxonomy (Classification) Source from Arctos to WoRMS via GN??  Would I still have access to the taxa (primarily terrestrial mollusca) that are in Arctos but not in WoRMS?  And as long as the taxa are in WoRMS, I wouldn't have to update Arctos at all or would we have to determine all taxa that are missing from Arctos and add them?

**Comment by dustymc** [comment]
That's an option. (And I think you can make the change.)

You'll always have access to the NAMES in Arctos. A specimen linked to a name which doesn't have data in your preferred classification would have no asserted classification data - it wouldn't be findable by eg, the "family' search field, would go to GBIF (et al) with no "taxonomy" data, etc. It would remain findable by anything linked to the name via "any taxon."

You would still have to add new NAMES to Arctos as you need them (or we could mass-add them from the worms dump or whatever), but Arctos would go looking for classification data - you wouldn't need to (or be able to) manage that locally.

**Comment by sharpphyl** [comment]
Let me reread your comment a few times and discuss with Bryan next week, but if I understand you correctly, I think I'd rather have WoRMS data in the local Arctos taxonomy.  Otherwise, if I haven't filled in a classification, the specimen basically becomes unfindable above the species level, which subverts the whole purpose of digitization.  With a bulk WoRMS upload, the taxonomy update just happens faster than if I add each taxon one by one when we need it over the next decade.

**Comment by dustymc** [comment]
That's not strictly true - it's findable (via classifications other than your preferred) by anyone who uses the "any taxon" thing (if that doesn't time out...) - but yes, you've got the idea.

**Comment by campmlc** [comment]
Is it not possible to add WORMS to Arctos? How many conflicts would there
be with existing Arctos taxa? Can we get a list by collection?

**Comment by Jegelewicz** [comment]
I don't know how much this would affect UTEP, but it would probably be an improvement.  Of course, I am really interested in the use of a non-Arctos classification. It could be that we would help improve WORMS if we had some taxa that had no classification there. How hard would it be to figure out what would be left hanging if they did use WORMS? Try it out in test?

**Comment by dustymc** [comment]
The intention has always (since NSF announced this thing called ITIS would be funded!) been to use an external source of taxonomy. It's never happened because we've never found one with usable data. I'd think WoRMS would welcome the help, and sharing with GlobalNames should be something they do anyway. No problem, right?!

There's really nothing to test - they have classifications for the names you need and can share them via GN or they don't/can't. It's exactly the same internal functionality as any other classification - it'll work in Arctos.

**Comment by campmlc** [comment]
But we have to choose between WORMS and Arctos? No way to upload their
current taxonomy into Arctos?

**Comment by sharpphyl** [comment]
Dusty, can you better explain the mechanism for getting all the mollusca taxa that WoRMS sends to GN into the Arctos taxonomy?  If you can do it through GN, that's great.  No need to work directly with WoRMS as long as they are updating GN regularly - and they appear to be now.  All we want is for all the WoRMS mollusca taxa to magically be in Arctos - both taxa that are new to Arctos and updates to existing taxa.  Right now, we can get all WoRMS taxa through GN but only manually and one at a time.  With a multitude of new and revised taxa in WoRMS but not in Arctos it will take us years to get the taxonomy up to date.

**Comment by dustymc** [comment]
I can't confirm anything without the data - I have no idea what's in there.

**Comment by campmlc** [comment]
Dusty, can we add WORMS in its entirety to test, so we can experiment with
it there?

**Comment by sharpphyl** [comment]
Our collection only needs the taxa in Mollusca - about 20% of WoRMS taxa.  Other collections may or may not want the other 80%.

**Comment by dustymc** [comment]
You can do whatever you want in test, but you'll probably need to let me know so I can turn some scripts back on if you're going to load classifications there.

I don't really see anything experimental here - lots of people have done all of this many times, it's just moving some data over (and adding some new names).

**Comment by dustymc** [comment]
You can't do that in the interfaces at the moment, but..

```
UAM@ARCTOSTE> update collection set PREFERRED_TAXONOMY_SOURCE ='World Register of Marine Species' where guid_prefix='MSB:Para';

1 row updated.

```

Arctos should figure it out and start refreshing within a couple days, but I'll get things going now.

This will work exactly like any other classification - if there are data which fit in flat they'll be stuffed in there and available for labels and searching and DWC sharing and all that jazz - you just can't edit taxonomy data now (because your edits would be replaced when Arctos pulls from GN; editing would be pointless and frustrating).

http://arctos-test.tacc.utexas.edu/guid/MSB:Para:16112 is going to be a wet mess because http://arctos-test.tacc.utexas.edu/name/Taenia#WorldRegisterofMarineSpecies - "order" will end up as NULL or "Porocephalida , Cyclophyllidea" or whatever happens when there's not a clear path to a single value, http://arctos-test.tacc.utexas.edu/guid/MSB:Para:21659 is going to pull from http://arctos-test.tacc.utexas.edu/name/Diphyllobothrium#WorldRegisterofMarineSpecies instead of http://arctos-test.tacc.utexas.edu/name/Diphyllobothrium#Arctos (so no real changes), etc.

**Comment by anna-chinn** [comment]
> Yes, each collection prefers a classification.

@dustymc : In Manage Collection, I can only choose between the two local classifications (https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source). Is this correct? Is there any way to select a non-local classification source?

**Comment by dustymc** [comment]
@anna-chinn the interface is currently limited to sources in http://arctos.database.museum/info/ctDocumentation.cfm?table=CTTAXONOMY_SOURCE. We can change that, or as above I can bypass the interfaces until we can change it. 

FYI here are current sources:

```
UAM@ARCTOS> select distinct source from taxon_term order by source;

SOURCE
------------------------------------------------------------------------------------------------------------------------
/home/dimus/files/dwca/zoological names.zip
3i - Typhlocybinae Database
Arctos
Arctos Plants
Arctos Relationships
Belgian Species List
BirdLife International
CATE Sphingidae
Catalogue of Life
Checklist da Flora de Portugal (Continental, Açores e Madeira)
Checklist of Beetles (Coleoptera) of Canada and Alaska. Second Edition.
Database of Vascular Plants of Canada (VASCAN)
FishBase Cache
Freebase
Freshwater Animal Diversity Assessment - Normalized export
GBIF Backbone Taxonomy
GRIN Taxonomy for Plants
Gymno
ITIS
Index Fungorum
Interim Register of Marine and Nonmarine Genera
NCBI
Open Tree of Life Reference Taxonomy
Sendoya S., Fernández F. AAT de hormigas (Hymenoptera: Formicidae) del Neotrópico 1.0 2004 (Spreadsheet)
The Interim Register of Marine and Nonmarine Genera
The International Plant Names Index
The Mammal Species of The World
The Paleobiology Database
The Reptile Database
Union 4
Wikispecies
WoRMS
World Register of Marine Species
iNaturalist

34 rows selected.
```

I'm not sure why there's so little intersection with http://resolver.globalnames.org/data_sources - first guess is that what's in Arctos represents only a small proportion of what's in GlobalNames. (That works both ways - ~85% of the names in Arctos are not in GlobalNames!)

**Comment by dustymc** [comment]
@campmlc FLAT is now caught up for MSB:Para at TEST. (Filtered_Flat/public data will take another ~hour or so).

```
UAM@ARCTOSTE> select phylorder from flat where guid='MSB:Para:16112';

PHYLORDER
------------------------------------------------------------------------------------------------------------------------
Cyclophyllidea, Porocephalida

1 row selected.
```

**Comment by sharpphyl** [comment]
We'll go ahead and request the WoRMS mollusca taxonomy.  It's available in JSON or XML.  Dusty, can you help us translate that to .csv and, if so, which format do you prefer?  Once we get it,  can you help us determine which collections would be impacted by the upload so we get their OK.  Thanks.

**Comment by dustymc** [comment]
JSON please.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/1826
