### ISSUE TITLE
Reporter issues

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2729]
I can't seem to get the reports I want to print. I was trying to print our DZTM prep sheets for this search: http://arctos.database.museum/saved/2020%2D1
and I get the following error:
![image](https://user-images.githubusercontent.com/12507297/83575776-87c10600-a4ed-11ea-8437-e4fc1b8b86f1.png)

 
**ERROR: function round(double precision, integer) does not exist--
 
The error occurred in /usr/local/httpd/htdocs/internal/reporter/report_printer.cfm: line 130
128 : 	 129 :	<cfquery name="d" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 
130 : 				#preservesinglequotes(sql)# 
131 : 			</cfquery> 132 : 		</cfcatch>**

The round function used to exist and work fine. I actually tried to print from multiple report templates (from multiple institutions) and almost all resulted in some kind of error. There were many other 'function does not exist' errors and some ORDER issues. The only reports that did produce a printout were the UWBM reports. I was going to download their report templates to try and troubleshoot, but downloading any reports from http://reports.arctos.database.museum/reporter/reporter.cfm?auth_key=F9C0F7B5-0E6A-4C00-AD6E028B59B7EFCE&pg=reporter
results in the following error:

_This site can’t be reached
The webpage at http://reports.arctos.database.museum/reporter/reporter.cfm?action=download&report_template=uam_mamm_loan.cfr&auth_key=F9C0F7B5-0E6A-4C00-AD6E028B59B7EFCE might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE_

**Comment by dustymc** [comment]
See also https://github.com/ArctosDB/PG-migration-testing/issues/16 and https://github.com/ArctosDB/PG-migration-testing/issues/127

It's not unexpected that untested reports won't work. I'm happy to help you rebuild them, just let me know the handler name.

PG is super-twitchy on datatype; ``round(dec_lat::numeric,5) DEC_LAT`` should work.

https://www.postgresql.org/docs/current/functions-math.html

You can only ORDER by returned columns, and the syntax is a bit different than Oracle.

https://www.postgresql.org/docs/current/sql-select.html

Download should be fixed, DZTM now prints.

**Comment by acdoll** [comment]
Thanks @dustymc - I forgot to search the PG-testing GitHub. I wonder if some issues should be migrated into this repository? 
It was really the inability to download templates that prompted this issue; but thanks for fixing my handler issue - that would have taken me while to figure out. These postgres resources look very helpful. I'll work on fixing the other DMNS handlers so I get a better sense of how this works (I'll still probably have to bug you) . Then maybe I'll be able to help others with theirs.

**Comment by dustymc** [comment]
recipes for fixing broken reports

---------------------------------------

Bad

```
decode(trim(flat.sex),
    'male','male',
    'female','female',
    '?') sex,
```

Good

```
case 
when trim(flat.sex)='male' then 'male'
when trim(flat.sex)='male' then 'male'
else '?'
end as sex,

```

-----------------------------------------

bad
```
to_number(cat_num)
```
good
```
cat_num::int
```

**Comment by campmlc** [comment]
I have tried to follow these instructions to fix an MSB:Para report. I changed the following as recommended above. 
     decode(trim(flat.sex),
    'male','male',
    'female','female',
    '?') sex,
Still doesn't work.
There are many things in the current handler that do not correspond to anything mentioned here. We have gone through and deleted the handlers for all reports in MSB:Para that are not currently needed. I would like to request that someone who understands SQL @dustymc  please fix these handlers so we can get the remaining reports to work.

**Comment by dustymc** [comment]
what is the report?

**Comment by campmlc** [comment]
msb_para_4dram_label_origID.cfr

**Comment by dustymc** [comment]
``when.trim`` should be ``when trim``

**Comment by campmlc** [comment]
Yay! Seems to be working. I'll try with other reports.

**Comment by campmlc** [comment]
OK, I'd like some advice on how to modify the above label template and handler to include the AF/IF/NK number or other collector/original ID. Also how to add in the related item scientific name - e.g. host info, and part lot count.

**Comment by campmlc** [comment]
Any way to get the following report SQL working?
report_id=5601110
MSB_Para_loan_invoice_NK_and_host

**Comment by dustymc** [comment]
I removed

``
    decode(trim(flat.sex),
``

**Comment by campmlc** [comment]
Thanks- but it is still cutting off the locality of the first record, and not pulling the hos info.  Can we fix and add in the following functionality:

1) Replace NK field with "Field number" (I can do this in the cfr file); then for the value,  select NK if available and add prefix "NK",  if not,  select AF and add prefix "AF"; if not, select IF and add prefix "IF"; if not, select collector number

2) Allow pull of host scientific name in host Other ID field (I will change this field to Host ID in the cfr); there is another issue somewhere - we need to pull the current host ID from related catalog items if such exists; if that relationship doesn't exist, pull "verbatim host ID".

**Comment by dustymc** [comment]
>cutting off the locality 

That's a layout issue - you can essentially have an infinite number fields each containing an infinite number of characters in an infinite number of data objects which you might call "the locality" - deciding what to ignore so you can squish that down to fit on a little piece of paper isn't something I can much help with.

https://github.com/ArctosDB/arctos/issues/3057#issuecomment-682168815 

https://github.com/ArctosDB/arctos/issues/3057#issuecomment-682882541

>if that relationship doesn't exist, pull "verbatim host ID".

That's not currently cached, and I'm not sure it's available publicly at all.

**Comment by campmlc** [comment]
Well, I tried to add the conditional language to MSB Para Loan Invoice and
messed it up.
Help?
