### ISSUE TITLE
Code Table Request - preservation "mount"

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#4090]
**Goal**

Normalize "mount" parts

**Context**

"Mount" is not a part name. Preservation seems most appropriate but still not great; I'm very open to better ideas.

**Table**

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation

**Value**

mount

**Definition**

Migrated from part name; presumably some taxidermy technique relevant to the taxon. Using this term is not recommended.

**Comment by Jegelewicz** [comment]
If we are going to include "preparations" in preservation, then I think it belongs here.

**Comment by AJLinn** [comment]
"Mount" is an exhibition support that is custom fit to an object. We added it as a part because when an object goes on exhibit and has a custom mount made for it (usually out of brass), we want to keep it associated with the object for the next time it goes on exhibit (it takes a lot of additional handling by someone to build a custom-fit exhibit mount and we want to decrease any extra handling).

Maybe we should instead adjust the part name to be "exhibit mount"?

**Comment by ewommack** [comment]
> For UAM:EH "Mount" is an exhibition support that is custom fit to an object. We added it as a part because when an object goes on exhibit and has a custom mount made for it (usually out of brass), we want to keep it associated with the object for the next time it goes on exhibit (it takes a lot of additional handling by someone to build a custom-fit exhibit mount and we want to decrease any extra handling).

Yep totally not what I would think if I saw the part name mount. I would think of a taxidermy animal of some sort. Definitely are going to need some really clear definitions. 
I would also get confused with "exhibit mount" = is this a taxidermy animal that is specific for an exhibit? @AJLinn is running into all of us animal people mucking up her nice part.

**Comment by Jegelewicz** [comment]
Paleo collections could also use "object mount" for the cradles they create for fossils in storage....because mounts aren't only used in exhibits. @Nicole-Ridgwell-NMMNHS

**Comment by dustymc** [comment]
English is not an unambiguous language; context is almost always necessary. Maybe we can make some things better by carefully selecting terminology, but ignoring the documentation (or not having useful documentation, as was the case here) just doesn't scale. 

I suspect many critter-parts which include "mount" (articulated, etc.) include some object(s) that could also be cataloged as a "mount" - and some of them are probably just for storage, not necessarily "exhibit." 

I don't have particular objections to changing the part name, but the critical part of this is the definition. 

"A device meant to position or display the object" ????

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Our plan is for cradles to be containers, BUT having them as parts would allow cradle and specimen to be separated yet still maintain that association of this cradle is for this specimen.

**Comment by campmlc** [comment]
Yes

**Comment by AJLinn** [comment]
> "A device meant to position or display the object" ????

This seems like a good general definition that would cover most of the uses currently considered by you "animal people."  ;-)

Is there a way to add a pick list (like Disposition) to indicate if it's an [exhibit](https://www.universityproducts.com/exhibit-display/display-cases-mounts), [storage](https://stashc.com/the-publication/supports/), [2D](https://framing4yourself.com/tutorial/how-sink-mount-canvas-board/), or [animal mount](https://all-taxidermy.com/product-category/taxidermy-mounts/)? [feel free to find other examples] This could help immediately clarify what kind of mount it is. We typically just write "exhibit mount" or "object mount" in the remarks field, but it would be nice to have a set of controlled vocabulary for clarity.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
How about: "A device meant to position, display, or support the object"?

> Is there a way to add a pick list (like Disposition) to indicate if it's an exhibit, storage, 2D, or animal mount?

Part attribute?

**Comment by Jegelewicz** [comment]
Code Table committee suggests:

part | new part | new part definition | new part preservation attribute | part condition addendum 
-- | -- | -- | -- | -- 
body mount | body | use existing definition | taxidermy | 
head mount | head | use existing definition | taxidermy | 
mount | mount | A device meant to position, display, or support the object. | | 
skeleton, mounted | skeleton | use existing definition | articulated | 
skeleton, postcranial, mounted | skeleton | use existing definition | articulated | postcranial 
skin, mounted | skin | use existing definition | taxidermy | 
skull, mounted | skull | use existing definition | articulated |

**Comment by Jegelewicz** [comment]
Added to AWG issues agenda 2021-12-02

**Comment by Jegelewicz** [comment]
For skeletal parts - change to mounted, but add articulated as well for all to use.

add A "manufactured" device to the mount definition

**Comment by AJLinn** [comment]
for clarity, can we use "manufactured or created" - manufacture is generally a mass-produced type of creation where custom-made things are simply "created" (put into being).

**Comment by Jegelewicz** [comment]
Changes to "mount" definition made and part name added for ES collections.

**Comment by Jegelewicz** [comment]
@dustymc new preservation attributes have been added. Should be good to go for all changes. Note that "mount" has only been available to EH collections so I don't expect that we will need to change any of those, but maybe we want to do a quick check of all "mount" parts to make sure they are what the new definition says they are? See migration here - https://github.com/ArctosDB/arctos/issues/4090#issuecomment-973327780

**Comment by dustymc** [comment]
Done.


Summary:

```
           part_name            | new_part_name | new_part_attr_type_1 | new_part_attr_val_1 | new_part_attr_type_2 | new_part_attr_val_2 |                new_part_remk_suffix                
--------------------------------+---------------+----------------------+---------------------+----------------------+---------------------+----------------------------------------------------
 skin, mounted                  | skin          | preservation         | taxidermy           |                      |                     | Original part name: skin, mounted
 skeleton, mounted              | skeleton      | preservation         | mounted             |                      |                     | Original part name: skeleton, mounted
 body mount                     | body          | preservation         | taxidermy           |                      |                     | Original part name: body mount
 head mount                     | head          | preservation         | taxidermy           |                      |                     | Original part name: head mount
 skeleton, postcranial, mounted | skeleton      | preservation         | mounted             | part modifier        | postcranial         | Original part name: skeleton, postcranial, mounted
 skull, mounted                 | skull         | preservation         | mounted             |                      |                     | Original part name: skull, mounted

```

Collections:

```

 guid_prefix | nrecs 
-------------+-------
 ACUNHC:Bird |    62
 APSU:Mamm   |     1
 ASNHC:Bird  |   152
 ASNHC:Mamm  |    73
 CHAS:Bird   |  1299
 CHAS:Herp   |     9
 CHAS:Mamm   |   236
 CHAS:Teach  |    74
 DMNS:Bird   |  2789
 DMNS:Herp   |     1
 DMNS:Mamm   |   442
 HMCM:Bird   |    13
 HMCM:Mamm   |     2
 MLZ:Bird    |     2
 MSB:Bird    |    18
 MSB:Mamm    |   106
 MVZ:Bird    |    12
 MVZ:Hild    |     1
 MVZ:Mamm    |     2
 NMMNH:Bird  |     9
 NMMNH:Herp  |     1
 NMMNH:Mamm  |    11
 NMMNH:Paleo |     2
 NMU:Bird    |     2
 NMU:Mamm    |     2
 OWU:Bird    |   532
 OWU:Mamm    |    38
 UAM:Bird    |     1
 UAM:Mamm    |    25
 UCM:Bird    |   533
 UCM:Fish    |     3
 UCM:Herp    |     1
 UCM:Mamm    |   141
 UCSC:Bird   |    52
 UCSC:Mamm   |     8
 UMNH:Bird   |   122
 UMNH:Herp   |     3
 UMNH:Mamm   |     2
 UMZM:Bird   |    67
 UMZM:Mamm   |    37
 UNR:Mamm    |     2
 UTEP:Bird   |     1
 UTEP:Mamm   |     4
 UTEP:Teach  |     1
 UWBM:Mamm   |    88
 UWYMV:Bird  |     1
 UWYMV:Mamm  |     1

```

Data:

[temp_mnt.csv.zip](https://github.com/ArctosDB/arctos/files/7898709/temp_mnt.csv.zip)

**Comment by acdoll** [comment]
@Jegelewicz @dustymc While discussing the use of 'body' for our taxidermy mounts with our curator (who _really_ does not like the change), I noticed the definition in [specimen_part_name](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name) really does not fit this usage for mounts. Maybe 'body' just needs a better definition, but are collections using that for things other than taxidermy mounts? 
Maybe we (DMNS) should consider using 'skin' with preservation 'taxidermy', but that still doesn't feel quite right. I think a part of 'taxidermy mount' would be most ideal, since that is what we're talking about and most people understand [that term](https://en.wikipedia.org/wiki/Taxidermy). I've not reopened this issue so you can convince me otherwise.

**Comment by Jegelewicz** [comment]
@acdoll this was discussed and we decided upon these usages - https://github.com/ArctosDB/arctos/issues/4090#issuecomment-973327780

body is problematic, along with carcass - see https://github.com/ArctosDB/arctos/issues/4368

As for "taxidermy mount" - what exactly is taxidermied? A head and shoulders? the whole thing? A leg? I still think that the part should be whatever is preserved and taxidermy is the preservation.

**Comment by ewommack** [comment]
> As for "taxidermy mount" - what exactly is taxidermied? A head and shoulders? the whole thing? A leg? I still think that the part should be whatever is preserved and taxidermy is the preservation.

Interesting question. I could definitely taxidermy any part of an animal, andI bet someone has already done it before me.
When I think of taxidermy, I think of an animal that is set in a life-like pose (or completely fantasical pose), separate from the consistent formation of round and flat skins, and skeletons produced for scientific collecting. Often that involves the use of hard and shaped cores of material, such as foam and plaster of paris. 
Not sure if that is the same for other people. @acdoll what do you think?

**Comment by acdoll** [comment]
I know it was discussed and decided but it still doesn't seem correct. 
Taxidermy is an amalgamation of various parts and non-specimen materials. Those specifics (head, shoulder) could just as easily go in as an attribute. Why use not-quite-right terms for something that has a specific term? It feels like we're adding unnecessary complexity that only heavy Arctos users can make use of. External researchers aren't going to know to extract JSON info contained in part details to find out if something is a mount (if they even had that column selected).
If body is problematic why did we go with that?

**Comment by acdoll** [comment]
Yes. I agree with that general definition, @ewommack, and I think most people familiar with natural history collections would too.

**Comment by dustymc** [comment]
Reopening, obviously needs more discussion.

Fixing the wiki copypasta definitions seems most useful at this point; I don't think they're reflective of the material, and they don't provide a common ground from which we can have productive discussions. I'm happy to eventually load it if someone wants to start a spreadsheet or something.

**Comment by droberts49** [comment]
I realize I'm coming into this conversation a few months behind and did not see this when it was brought up -- I'm really not happy with how the part name for mounted specimens was changed. This affects many specimens in our collection, and we do need a clear way to distinguish between a study skin, mounted specimen, tanned skin, etc. All of these original part names are now dumped into the parts remarks field and this is not an easy way to search through a bunch of specimen records for specific types of specimens.

**Comment by droberts49** [comment]
In the code table for specimen parts, there are recommendations for transitioning things into a preservation category, e.g. skin, tanned -- "consider using skin with tanned as preservation". Why wasn't this done for "skin, mounted"? I need specimens in our collection to be searchable and distinguishable by their preparation as a study skin, mounted specimen, etc, not just "taxidermy"; to me, that is the general preparation method used and doesn't indicate what kind of taxidermied creation I'm looking for.

@dustymc  please put all the "Original part name: skin, mounted" that got put into the parts remark field into a field that can be search by specific terms. It is immensely unhelpful to have this in a memo type field where we have other pieces of information. This can go into a preservation field, but will need to be normalized so that it is searchable. If there is a need to separate the part from the preservation style, then I suggest more descriptive terms be used. "study" on its own as a preservation style is not understandable.
taxidermy, mount
taxidermy, study skin
tanned skin

**Comment by Jegelewicz** [comment]
> All of these original part names are now dumped into the parts remarks field and this is not an easy way to search through a bunch of specimen records for specific types of specimens.

That should not be the case? These should all include a preservation attribute. If they don't, we should discuss.

**Comment by droberts49** [comment]
@Jegelewicz  We have many mounted specimens that were in Arctos before there was any type of preservation field, and when the preservation field was added, these were given "taxidermy" as the value. I need a way to distinguish and search on parameters of the type of specimen we're looking for in the data. We may want a mounted specimen and not a study skin for an exhibit, a program, or an artist visit. 

There needs to be ways to distinguish whether a "skin" is in fact a study skin, mounted specimen, shmoo, tanned hide, flat skin, etc. Similarly, a "skeleton" type needs to also indicate whether it is a box of bones or an articulated/mounted skeleton.

**Comment by Jegelewicz** [comment]
> There needs to be ways to distinguish whether a "skin" is in fact a study skin, mounted specimen, shmoo, tanned hide, flat skin, etc. Similarly, a "skeleton" type needs to also indicate whether it is a box of bones or an articulated/mounted skeleton.

There is

part name | part preservation
 --  | -- 
[skin, study](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skin__study) | 
[skin](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skin) | [taxidermy](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation#taxidermy)
[skin, shmoo](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skin__shmoo) | 
[skin, tanned](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skin__tanned) | 
[skin, flat](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skin__flat) | 
[skeleton](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skeleton) | 
[skeleton](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name#skeleton) | [articulated](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation#articulated)

I don't know what I am missing, except that whatever was in remarks perhaps did not translate to the proper mix of part name and preservation?

However, this also points out that we are not done removing preservation from part - all those "skin, X" need to be fixed.

**Comment by wellerjes** [comment]
> all those "skin, X" need to be fixed.

Does this need to be fixed manually? Or can a backup be reinstated?

**Comment by Jegelewicz** [comment]
> Does this need to be fixed manually? Or can a backup be reinstated?

These have always been this way, but should be updated to skin with the term after the comma added as a preservation. It needs a whole new issue and community consensus first though.....

**Comment by dustymc** [comment]
The remaining skin discussion is (stuck at) https://github.com/ArctosDB/arctos/issues/4049.

I don't think I understand what's being requested, suggest a new/focused issue if something's still outstanding.

The just-before-update data above should be compatible with appropriate bulkloaders if something else needs adjusting.

Very tentatively reclosing....
