### ISSUE TITLE
Arctos Down - Arctos not responding 3/22/2024

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#7599]
Please complete to the best of your ability.

## Unplanned Outage
 - Friday 3/22/2024 Pacific at 1:40pm
 - No response at all - just spins and spins

## Communication before/during outage
- [x] Pin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG  
- [ ] Tweet @lin-fred (@mkoo backup)

## Communication after outage
- [x] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by KatherineLAnderson** [comment]
Same here, thanks for posting Carla.

**Comment by ewommack** [comment]
Down in WY too

**Comment by lin-fred** [comment]
Its up for me

**Comment by ewommack** [comment]
back in WY!

**Comment by KatherineLAnderson** [comment]
back in Seattle! woo!

**Comment by campmlc** [comment]
Back in NM

**Comment by dustymc** [comment]
still some crazy in the DB, things may go down again before this is resolved

**Comment by campmlc** [comment]
Back down again in NM. How long is outage estimate? Should I let students go home?

**Comment by ewommack** [comment]
oop down in WY again, I'll go work on an application

**Comment by dustymc** [comment]
> let students go home?

Only the ones who paid into the 'kill Arctos so we can go home early' fund.

>How long

Until the DB folks say it's safe. (I suspect not too long, but there's some problem they're trying to track down and who knows where that'll lead.)

**Comment by AJLinn** [comment]
Still seeing a 503 here in AK. Two hours of work time for students still!

**Comment by dustymc** [comment]
Arctos is back up, hopefully for good.

**Comment by ccicero** [comment]
Yep, working for me!
